[manager]
prepend_keymap = [
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
    { on = "I", run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    #{ on = [ "p" ], run = "plugin smart-paste" },
	{ on = ["g", "w"], run = "cd ~/work", desc = "工作目录" },
	{ on = ["g", "f"], run = "cd ~/.config", desc = "工作目录" },
	{ on = "<c-g>", run = "plugin lazygit", desc = "Move cursor up" },
]
[tasks]
prepend_keymap = [
  { on = "i", run = "arrow -1", desc = "Move cursor up" },
]

[select]
prepend_keymap = [
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
]

[input]
prepend_keymap = [
  { on = "k", run = "insert",                              desc = "Enter insert mode" },
  { on = "K", run = [ "move -999", "insert" ],             desc = "Move to the BOL, and enter insert mode" },
]

[confirm]
prepend_keymap = [
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
]

[help]
prepend_keymap = [
  { on = "i", run = "arrow -1", desc = "Move cursor up" },
]
